# dvc.yaml
stages:
    # 1. 資料處理
    preprocess:
        cmd: python src/features.py
        deps:
        - data/raw/events.csv
        - src/features.py
        - params.yaml
        outs:
        - data/processed/train.csv
        - data/processed/test.csv

    # 2. 訓練 Baseline (熱門推薦) - 選擇性保留
    train_baseline:
        cmd: python src/train_baseline.py
        deps:
        - data/processed/train.csv
        - src/train_baseline.py
        outs:
        - models/baseline_top10.json

    # 3. 訓練 Transformer 模型
    train:
        cmd: python src/train.py
        deps:
        - data/processed/train.csv
        - data/processed/test.csv
        - src/train.py
        - src/model.py
        - params.yaml
        outs:
        - model.pth
        - item_map.json

    # 4. 評估階段 (生成 Metrics)
    evaluate:
        cmd: python src/evaluate.py
        deps:
        - src/evaluate.py
        - src/model.py
        - data/processed/test.csv
        - params.yaml
        - model.pth      # 明確依賴模型檔案
        - item_map.json  # 明確依賴 Mapping
        metrics:
        - metrics.json:
            cache: false