stages:
    preprocess:
        cmd: python src/features.py
        deps:
        - src/features.py
        - params.yaml
        - feature/events_processed.csv  
        - data/raw/meta_Beauty.json.gz
        outs:
        - data/processed/train.csv
        - data/processed/test.csv
        - artifacts/item_map.json         
        - artifacts/items_metadata.json   

    train:
        cmd: python src/train_by_AWS.py
        deps:
        - src/train_by_AWS.py
        - src/train.py
        - src/model.py
        - params.yaml
        - data/processed/train.csv # 根據你實際的依賴路徑
        - data/processed/test.csv
    # 注意：移除本地的 outs (例如 artifacts/model.pth)
    # 因為模型現在是直接儲存在 S3 並由 MLflow 進行版控，本地不會產生模型實體檔案。             

    evaluate:
        cmd: python src/evaluate.py
        deps:
        - src/evaluate.py
        - src/model.py
        - data/processed/test.csv
        - params.yaml
        - artifacts/model.pth             
        - artifacts/item_map.json        
        metrics:
        - metrics/metrics.json:
            persist: true
            cache: false