stages:
    # 1. 資料處理 (ETL) - 現在包含價格修復
    preprocess:
        cmd: python src/features.py
        deps:
        - src/features.py
        - params.yaml
        # 若資料來源是來自特定檔案，可以保留這些 deps，
        # DVC 會偵測這些檔變更才重新執行
        - data/raw/meta_Beauty.json.gz.dvc 
        outs:
        - data/processed/train.csv
        - data/processed/test.csv
        - item_map.json
        - items_metadata.json # 確保 features.py 產生這個

    # 2. 訓練 Transformer 模型
    train:
        cmd: python src/train.py
        deps:
        - data/processed/train.csv
        - data/processed/test.csv
        - src/train.py
        - src/model.py
        - params.yaml
        - item_map.json
        outs:
        - model.pth

    # 3. 評估階段
    evaluate:
        cmd: python src/evaluate.py
        deps:
        - src/evaluate.py
        - src/model.py
        - data/processed/test.csv
        - params.yaml
        - model.pth
        - item_map.json
        metrics:
        - metrics.json:
            persist: true
            cache: false