stages:
    # 1. 資料處理 (ETL)
    preprocess:
        cmd: python src/features.py
        deps:
        - src/features.py
        - params.yaml
        - data/raw/reviews_Beauty_5.json.gz  # 改為追蹤新的資料集
        - data/raw/meta_Beauty.json.gz
        outs:
        - data/processed/train.csv
        - data/processed/test.csv
        - item_map.json           # output
        - items_metadata.json     # output

    # 2. 訓練 Transformer 模型
    train:
        cmd: python src/train.py
        deps:
        - data/processed/train.csv
        - data/processed/test.csv
        - src/train.py
        - src/model.py
        - params.yaml
        - item_map.json           # train.py 需要讀取這個來知道 num_items
        outs:
        - model.pth

    # 3. 評估階段
    evaluate:
        cmd: python src/evaluate.py
        deps:
        - src/evaluate.py
        - src/model.py
        - data/processed/test.csv
        - params.yaml
        - model.pth
        - item_map.json
        metrics:
        - metrics.json:
            cache: false