stages:
  preprocess:
    cmd: python src/features.py
    deps:
    - data/raw/events.csv
    - src/features.py
    outs:
    - features/events_processed.csv
  train:
    cmd: python src/train.py
    deps:
    - features/events_processed.csv
    - src/train.py
    outs:
    - models/popular_items.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/raw/events.csv
    - models/popular_items.pkl
    - src/evaluate.py
    outs:
    - metrics/metrics.json
