stages:
    preprocess:
        cmd: python src/features.py
        deps:
        - src/features.py
        - params.yaml
        - feature/events_processed.csv  
        - data/raw/meta_Beauty.json.gz
        outs:
        - data/processed/train.csv
        - data/processed/test.csv
        - artifacts/item_map.json         
        - artifacts/items_metadata.json   

    train:
        cmd: python src/train_by_AWS.py
        deps:
        - src/train_by_AWS.py
        - src/train.py
        - src/model.py
        - params.yaml
        - data/processed/train.csv
        - data/processed/test.csv

    export:
        cmd: python src/export_model.py
        deps:
        - src/export_model.py
        - src/model.py
        - artifacts/model.pth
        - artifacts/item_map.json
        outs:
        - artifacts/model.onnx
        - artifacts/model.engine

    evaluate:
        cmd: python src/evaluate.py
        deps:
        - src/evaluate.py
        - src/model.py
        - data/processed/test.csv
        - params.yaml
        - artifacts/model.pth             
        - artifacts/item_map.json
        - artifacts/model.onnx        
        metrics:
        - metrics/metrics.json:
            persist: true
            cache: false